server:
  port: 38080

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usersdb?serverTimeZone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#  redis:
#    host: localhost
#    port: 36381
#    jedis:
#      pool:
#        max-idle: 16
#        min-idle: 0
#        max-active: 8
#        max-wait: -1
#        timeout: 0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

allowed:
  origin: http://localhost:9527

jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "qwertyuiop7418520" #密钥
  expireTime: 60 #token有效时间 (分钟) 建议一小时以上

upload:
  file:
    path: E:/static/